# This is a generated file. Not intended for manual editing.
services:
  backendlab1:
    build:
      context: "C:\\Users\\schri\\RiderProjects\\BackendLab1"
      dockerfile: "BackendLab1/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "backendlab1:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "C:\\Users\\schri\\RiderProjects\\BackendLab1\\BackendLab1:/app:rw"
    - "C:\\Users\\schri\\RiderProjects\\BackendLab1:/src:rw"
    - "C:\\Users\\schri\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\schri\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.2.2\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files (x86)\\JetBrains\\JetBrains Rider 2025.1.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\schri\\AppData\\Local\\JetBrains\\Rider2025.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_10_07_21_10_30:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
